title: "HikingDuo - Travel Blog"
email: "hikingduoofficial@gmail.com"
description: "HikingDuo - Travel Blog helping others to help travel more."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.hikingduo.com/"
permalink: "/:title"
instagram_username: "joyfulodyssey"
instagram_url: "https://www.instagram.com/joyfulodyssey/"
facebook_url: "https://www.facebook.com/thehikingduo"
youtube_url: "https://www.youtube.com/channel/UCTpUx4XMG9E49csxl1XkGBg"
site_logo: "/assets/images/hikinglogo.png"
white_logo: "/assets/images/hikinglogo.png"
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"

copyright_text: "&copy; copyright all reserved to <a href='https://www.hikingduo.com/'>hikingduo.com</a> © 2024"

author_info:  
  - name: "HikingDuo"
    designation: "Travel Blogger"
    bio: "Welcome to HikingDuo, your ultimate destination for adventure, exploration, and the thrill of the great outdoors. We are Saurabh and Ramya, passionate explorers on a mission to explore the world and uncover hidden gems along the way. Through our blog, we share travel guides, hiking tips, and captivating stories to inspire you to step out of your comfort zone and embrace the thrill of exploration."
    website: "https://www.hikingduo.com/"
    image: "/assets/images/profilephoto.jpg"
    signature: "/assets/images/signaturesnap.png"
    instagram_username: "joyfulodyssey"
    instagram_url: "https://www.instagram.com/joyfulodyssey/"
    facebook_url: "https://www.facebook.com/thehikingduo"
    youtube_url: "https://www.youtube.com/channel/UCTpUx4XMG9E49csxl1XkGBg"
# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache


paginate: 10
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:title/"

feed:
  collections:
    posts:
      path: "/index.xml"

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'category'
    values:
      layout: "category"
      show_meta: false 	# Hide metadata for all pages
      comments: false
